apiVersion: v1
kind: Secret
metadata:
  name: pipeline-credentials
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: CHANGE_ME
  password: CHANGE_ME
