apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: detect-secrets
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/displayName: "detect secrets"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task (based on IBM detect-secrets) is designed for detecting secrets within a code base.
  workspaces:
    - name: git-repo
      description: The git repo that has been cloned onto the volume backing this Workspace.
  params:
    - name: detectSecretsImage
      description: The image providing the detect-secrets binary that this Task runs.
      type: string
      default: "quay.io/noesamaille0/detect-secrets:0.0.2"
  results: []
  steps:
    - name: detect-secrets
      image: "$(params.detectSecretsImage)"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      script: |
        #!/usr/bin/env sh
        detect-secrets scan --all-files --use-all-plugins --update .secrets.baseline /app
        detect-secrets audit .secrets.baseline --report --fail-on-unaudited
