apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: detect-secrets
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/displayName: "detect secrets"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task, based on IBM detect-secrets (https://github.com/IBM/detect-secrets), is designed for detecting secrets in a code base.
  workspaces:
    - name: source
      description: The git repo that has been cloned onto the volume backing this Workspace.
  params:
    - name: image
      description: The image providing the detect-secrets binary that this Task runs.
      type: string
      default: "quay.io/noesamaille0/detect-secrets:0.0.4"
  results: []
  steps:
    - name: detect-secrets
      image: "$(params.image)"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      script: |
        #!/usr/bin/env sh
        ls -la /workspace
        ls -la /workspace/source
        cp -R /workspace/source ./app
        cd ./app
        detect-secrets scan --all-files --exclude-files package-lock.json --use-all-plugins --update .secrets.baseline
        detect-secrets audit .secrets.baseline --report --fail-on-unaudited
